name: "Mayastor tests"
on:
  pull_request:
    paths-ignore:
  push:
    branches:
      - cas-235
jobs:
  Build_and_run_cargo:
    name: Build and run cargo tests
    runs-on: self-hosted
    timeout-minutes: 20
    container:
      image: docker.io/mayadata/ms-buildenv:nix
      options: --privileged -v /dev:/dev -v /bin:/host/bin -v /lib/modules:/lib/modules
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          # this does not pin the compiler version
          toolchain: stable
      - run: ln -s /host/bin/kmod /bin/modprobe
      - run: /bin/modprobe nbd
      - run: /bin/modprobe xfs
      - run: /bin/modprobe nvme_tcp
      - run: echo 8192 | tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
      - run: rm mayastor/.cargo/config
      - run: rm nvmeadm/.cargo/config
      - run: cargo build --all
      - run: ( cd jsonrpc && cargo test )
      - run: ( cd mayastor && cargo test -- --test-threads=1 )
      - run: mkdir ./target/debug/github-artifacts/
      - run: ( cd ./target/debug/ && cp mayastor mayastor-client mayastor-agent spdk initiator mctl github-artifacts/ )
      - run: ( cd nvmeadm && cargo test )
      - uses: actions/upload-artifact@v2
        with:
          name: mayastor
          path: ./target/debug/github-artifacts
  Build_and_test_moac:
    name: Build and run moac tests
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:nix
    steps:
      - uses: actions/checkout@v2
      # npm prepare is normally done by npm install but not if run as a root
      - run: cd csi/moac && npm install && npm run-script prepare
      - run: cd csi/moac && npm test
  Test_mayastor_with_mocha:
    needs: Build_and_run_cargo
    name: Run mocha tests
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:nix
      options: --privileged -v /dev:/dev -v /bin:/host/bin -v /lib/modules:/lib/modules --cpus 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: mayastor
          path: ./target/debug
      - run: ( cd target/debug/ && chmod a+x mayastor mayastor-client mayastor-agent spdk initiator mctl )
      - run: ln -s /host/bin/kmod /bin/modprobe
      - run: /bin/modprobe nbd
      - run: /bin/modprobe xfs
      - run: echo 8192 | tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
      - run: ( cd mayastor-test && npm install)
      - run: ( cd mayastor-test && ./node_modules/mocha/bin/mocha test_cli.js )
      - run: ( cd mayastor-test && ./node_modules/mocha/bin/mocha test_replica.js )
      - run: ( cd mayastor-test && ./node_modules/mocha/bin/mocha test_csi.js )
      - run: ( cd mayastor-test && ./node_modules/mocha/bin/mocha test_csi_nbd.js )
      - run: ( cd mayastor-test && ./node_modules/mocha/bin/mocha test_csi_iscsi.js )
      - run: ( cd mayastor-test && ./node_modules/mocha/bin/mocha test_nexus.js )
      - run: ( cd mayastor-test && ./node_modules/mocha/bin/mocha test_rebuild.js )
